### ISSUE TITLE
Feature request: reset inventory switch in worldspawn

### ISSUE THREAD

**Issue by mariteaux** [dumptruckDS/progs_dump#13]
At present, the only way to spawn the player with no weapons on map change would be through the rune + info_player_start2 hack. I think it's within the scope of the project to add a worldspawn switch that causes the player to spawn without any of their prior weapons or ammo no matter what.

**Comment by dumptruckDS** [comment]
something similar to:

`void() ResetPlayerStuff =
{
	if (world.reset_player == 1)
	{
		SetNewParms ();
		return;
	}`
